name: Package to ghcr.io
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    types: ["review_requested"]
jobs:
  go-package-docker-image:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        # os: ["ubuntu-latest", "windows-latest","macOS-latest"]
        go-version: ["1.21"]
        # go-version: ["1.19", "1.20", "1.21.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      # run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Go dependencies
      working-directory: ./go_site
      run: go get .
    - name: Build Go package to test buildability
      working-directory: ./go_site
      run: go build -v ./...
    - name: Test with the Go CLI
      working-directory: ./go_site
      run: go test -v
    - name: Build the Gin and ginmetrics -> Go Docker image
      run: |
              docker build ./go_site --tag ghcr.io/florina-alfred/proposal:latest
              docker push ghcr.io/florina-alfred/proposal:latest
              docker tag ghcr.io/florina-alfred/proposal:latest  ghcr.io/florina-alfred/proposal:go-${{ steps.vars.outputs.sha_short }}
              docker push ghcr.io/florina-alfred/proposal:go-${{ steps.vars.outputs.sha_short }}        
    
