name: Package to ghcr.io
on:
  push:
    branches:
      - main
jobs:
    package-docker-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        strategy:
          matrix:
            python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        steps:
        - uses: actions/checkout@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.TOKEN }}
        - name: Set outputs
          id: vars
          run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        # Python
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r py_site/requirements.txt
        - name: Test with pytest
          run: |
            pip install pytest pytest-cov
            pytest py_site/app/tests_main.py
        - name: Lint with Ruff
          run: |
            pip install ruff
            ruff --output-format=github .
          continue-on-error: true
        - name: Build the FastAPI, uvicorn and CV2 python Docker image
          run: |
                 docker build ./py_site --tag ghcr.io/florina-alfred/proposal:py-${{ steps.vars.outputs.sha_short }}
                 docker push ghcr.io/florina-alfred/proposal:py-${{ steps.vars.outputs.sha_short }}
        - name: Build actix_web, actix_web_prom and serde
          run: |
                 docker build ./rust_site --tag ghcr.io/florina-alfred/proposal:rust-${{ steps.vars.outputs.sha_short }}
                 docker push ghcr.io/florina-alfred/proposal:rust-${{ steps.vars.outputs.sha_short }}
        - name: Build the Gin and ginmetrics
          run: |
                 docker build ./go_site --tag ghcr.io/florina-alfred/proposal:latest
                 docker push ghcr.io/florina-alfred/proposal:latest
                 docker tag ghcr.io/florina-alfred/proposal:latest  ghcr.io/florina-alfred/proposal:go-${{ steps.vars.outputs.sha_short }}
                 docker push ghcr.io/florina-alfred/proposal:go-${{ steps.vars.outputs.sha_short }}