name: Package to ghcr.io
on:
  push:
    branches:
      - main
jobs:
    python-docker-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write  
        steps:
        - uses: actions/checkout@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.TOKEN }}
        - name: Set outputs
          id: vars
          run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        - name: Build the FastAPI, uvicorn and CV2 python Docker image
          run: |
                 docker build . --tag ghcr.io/florina-alfred/proposal:latest
                 docker push ghcr.io/florina-alfred/proposal:latest
                 docker tag ghcr.io/florina-alfred/proposal:latest  ghcr.io/florina-alfred/proposal:${{ steps.vars.outputs.sha_short }}
                 docker push ghcr.io/florina-alfred/proposal:${{ steps.vars.outputs.sha_short }}
